import { Policy, Claim, AgentActivity, ProtocolRisk, VaultStats, X402Payment } from '@/types';

export const vaultStats: VaultStats = {
  totalValueLocked: 2_450_000,
  totalPolicies: 147,
  activeClaims: 12,
  totalPremiumsCollected: 185_000,
  totalClaimsPaid: 42_000,
  reserveRatio: 0.89,
  agentTransactions: 1_284,
};

export const protocols: ProtocolRisk[] = [
  {
    protocol: 'CasperSwap',
    riskScore: 23,
    tvl: 12_500_000,
    change24h: -2.3,
    alerts: [],
    lastUpdated: new Date().toISOString(),
    category: 'low',
  },
  {
    protocol: 'CSPR.trade',
    riskScore: 34,
    tvl: 8_200_000,
    change24h: 1.5,
    alerts: ['Unusual volume spike detected'],
    lastUpdated: new Date().toISOString(),
    category: 'medium',
  },
  {
    protocol: 'FriendlyMarket',
    riskScore: 67,
    tvl: 3_100_000,
    change24h: -12.4,
    alerts: ['Liquidity pool imbalance', 'Large withdrawal pending'],
    lastUpdated: new Date().toISOString(),
    category: 'high',
  },
  {
    protocol: 'CasperLend',
    riskScore: 18,
    tvl: 15_800_000,
    change24h: 0.8,
    alerts: [],
    lastUpdated: new Date().toISOString(),
    category: 'low',
  },
  {
    protocol: 'StakeVault',
    riskScore: 45,
    tvl: 5_600_000,
    change24h: -5.2,
    alerts: ['Validator set change detected'],
    lastUpdated: new Date().toISOString(),
    category: 'medium',
  },
  {
    protocol: 'NexusDEX',
    riskScore: 82,
    tvl: 1_200_000,
    change24h: -18.7,
    alerts: ['Smart contract vulnerability reported', 'TVL dropping rapidly', 'Whale exit detected'],
    lastUpdated: new Date().toISOString(),
    category: 'critical',
  },
];

export const policies: Policy[] = [
  {
    id: 'POL-001',
    holder: 'Alice.cspr',
    walletAddress: '01a3b5c7d9e1f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0',
    protocolCovered: 'CasperSwap',
    coverageAmount: 50_000,
    premiumRate: 0.025,
    premiumPaid: 1_250,
    status: 'active',
    riskScore: 23,
    startDate: '2026-06-01',
    endDate: '2026-09-01',
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'POL-002',
    holder: 'Bob.cspr',
    walletAddress: '02b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a1',
    protocolCovered: 'FriendlyMarket',
    coverageAmount: 25_000,
    premiumRate: 0.065,
    premiumPaid: 1_625,
    status: 'active',
    riskScore: 67,
    startDate: '2026-06-10',
    endDate: '2026-09-10',
    createdAt: '2026-06-10T14:30:00Z',
  },
  {
    id: 'POL-003',
    holder: 'Charlie.cspr',
    walletAddress: '03c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9a1b3c5',
    protocolCovered: 'NexusDEX',
    coverageAmount: 10_000,
    premiumRate: 0.085,
    premiumPaid: 850,
    status: 'claimed',
    riskScore: 82,
    startDate: '2026-06-05',
    endDate: '2026-09-05',
    createdAt: '2026-06-05T09:15:00Z',
  },
  {
    id: 'POL-004',
    holder: 'Diana.cspr',
    walletAddress: '04d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4',
    protocolCovered: 'CasperLend',
    coverageAmount: 100_000,
    premiumRate: 0.018,
    premiumPaid: 1_800,
    status: 'active',
    riskScore: 18,
    startDate: '2026-06-15',
    endDate: '2026-12-15',
    createdAt: '2026-06-15T11:45:00Z',
  },
  {
    id: 'POL-005',
    holder: 'Eve.cspr',
    walletAddress: '05e7f9a1b3c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7',
    protocolCovered: 'StakeVault',
    coverageAmount: 35_000,
    premiumRate: 0.045,
    premiumPaid: 1_575,
    status: 'active',
    riskScore: 45,
    startDate: '2026-06-20',
    endDate: '2026-09-20',
    createdAt: '2026-06-20T16:00:00Z',
  },
];

export const claims: Claim[] = [
  {
    id: 'CLM-001',
    policyId: 'POL-003',
    claimant: 'Charlie.cspr',
    amount: 8_500,
    reason: 'Smart contract exploit on NexusDEX resulted in loss of deposited funds',
    evidence: 'TX: 0x7a8b9c...deploy hash showing fund drainage from pool',
    status: 'approved',
    aiAssessment: {
      riskScore: 92,
      confidence: 0.94,
      recommendation: 'approve',
      reasoning: 'On-chain evidence confirms exploit. NexusDEX contract vulnerability verified. Claimant funds were in affected pool at time of exploit.',
      factors: [
        { name: 'On-chain Evidence', score: 95, weight: 0.35, description: 'Deploy hash verified, fund movement confirmed' },
        { name: 'Protocol Risk History', score: 88, weight: 0.25, description: 'NexusDEX had prior vulnerability reports' },
        { name: 'Claim Amount Validity', score: 90, weight: 0.20, description: 'Amount within coverage limits and matches losses' },
        { name: 'Timing Consistency', score: 96, weight: 0.20, description: 'Claim filed within 24h of exploit event' },
      ],
    },
    submittedAt: '2026-06-25T08:00:00Z',
    resolvedAt: '2026-06-25T08:02:30Z',
    txHash: '0xpayout_7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7',
  },
  {
    id: 'CLM-002',
    policyId: 'POL-002',
    claimant: 'Bob.cspr',
    amount: 5_000,
    reason: 'Impermanent loss exceeding threshold due to sudden liquidity drain',
    evidence: 'Pool ratio shifted from 50:50 to 95:5 within 30 minutes',
    status: 'reviewing',
    aiAssessment: {
      riskScore: 58,
      confidence: 0.72,
      recommendation: 'review',
      reasoning: 'Impermanent loss is within possible market conditions. Need to verify if manipulation occurred or if this was organic market movement.',
      factors: [
        { name: 'On-chain Evidence', score: 65, weight: 0.35, description: 'Pool ratio change confirmed but causation unclear' },
        { name: 'Market Conditions', score: 45, weight: 0.25, description: 'Broader market was volatile during period' },
        { name: 'Manipulation Indicators', score: 70, weight: 0.25, description: 'Some wash trading patterns detected' },
        { name: 'Policy Terms', score: 52, weight: 0.15, description: 'IL coverage has specific threshold requirements' },
      ],
    },
    submittedAt: '2026-06-26T14:20:00Z',
  },
  {
    id: 'CLM-003',
    policyId: 'POL-001',
    claimant: 'Alice.cspr',
    amount: 12_000,
    reason: 'Oracle manipulation caused incorrect swap rate',
    evidence: 'Price feed deviated 40% from market rate for 3 blocks',
    status: 'pending',
    submittedAt: '2026-06-27T09:00:00Z',
  },
];

export const agentActivities: AgentActivity[] = [
  {
    id: 'ACT-001',
    agentName: 'RiskSentinel',
    agentType: 'risk-monitor',
    action: 'Protocol Risk Assessment',
    details: 'Scanned NexusDEX smart contracts — CRITICAL vulnerability detected in liquidity pool withdrawal function',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    status: 'warning',
    gasUsed: 0.45,
  },
  {
    id: 'ACT-002',
    agentName: 'ClaimBot',
    agentType: 'claim-processor',
    action: 'Auto-processed Claim CLM-001',
    details: 'Verified on-chain evidence, cross-referenced with exploit database. Payout of 8,500 CSPR authorized and executed.',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    status: 'success',
    txHash: '0xpayout_7a8b9c...',
    gasUsed: 2.3,
  },
  {
    id: 'ACT-003',
    agentName: 'UnderwriteAI',
    agentType: 'underwriter',
    action: 'Policy Premium Recalculation',
    details: 'Adjusted FriendlyMarket coverage premiums from 4.5% to 6.5% based on increased risk signals',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    status: 'info',
  },
  {
    id: 'ACT-004',
    agentName: 'VaultKeeper',
    agentType: 'vault-manager',
    action: 'Reserve Rebalance',
    details: 'Moved 15,000 CSPR from yield pool to claims reserve to maintain 89% reserve ratio',
    timestamp: new Date(Date.now() - 450000).toISOString(),
    status: 'success',
    txHash: '0xrebalance_abc123...',
    gasUsed: 1.8,
  },
  {
    id: 'ACT-005',
    agentName: 'RiskSentinel',
    agentType: 'risk-monitor',
    action: 'Whale Movement Alert',
    details: 'Detected 500,000 CSPR withdrawal from StakeVault — monitoring for cascading effects',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    status: 'warning',
  },
  {
    id: 'ACT-006',
    agentName: 'ClaimBot',
    agentType: 'claim-processor',
    action: 'Claim Assessment Started',
    details: 'Analyzing CLM-002 from Bob.cspr — gathering on-chain evidence for impermanent loss claim',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    status: 'info',
  },
  {
    id: 'ACT-007',
    agentName: 'UnderwriteAI',
    agentType: 'underwriter',
    action: 'x402 Premium Payment Received',
    details: 'Micropayment of 1,250 CSPR received from Alice.cspr via x402 protocol for policy POL-001 renewal',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    status: 'success',
    txHash: '0xpremium_def456...',
    gasUsed: 0.12,
  },
  {
    id: 'ACT-008',
    agentName: 'RiskSentinel',
    agentType: 'risk-monitor',
    action: 'MCP Query — Block Analysis',
    details: 'Queried Casper MCP Server for blocks 1,245,000-1,245,050. No anomalies detected in CasperLend transactions.',
    timestamp: new Date(Date.now() - 1500000).toISOString(),
    status: 'success',
    gasUsed: 0.02,
  },
];

export const x402Payments: X402Payment[] = [
  {
    id: 'X402-001',
    from: 'RiskSentinel',
    to: 'CasperMCPServer',
    amount: 0.005,
    purpose: 'Block data query (blocks 1,245,000-1,245,050)',
    timestamp: new Date(Date.now() - 1500000).toISOString(),
    status: 'completed',
  },
  {
    id: 'X402-002',
    from: 'ClaimBot',
    to: 'CSPR.trade MCP',
    amount: 0.01,
    purpose: 'Historical trade data for CLM-002 evidence verification',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    status: 'completed',
  },
  {
    id: 'X402-003',
    from: 'Alice.cspr',
    to: 'InsuranceVault',
    amount: 1250,
    purpose: 'Policy POL-001 premium payment',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    status: 'completed',
  },
  {
    id: 'X402-004',
    from: 'InsuranceVault',
    to: 'Charlie.cspr',
    amount: 8500,
    purpose: 'Claim CLM-001 payout',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    status: 'completed',
  },
  {
    id: 'X402-005',
    from: 'UnderwriteAI',
    to: 'ExternalOracle',
    amount: 0.008,
    purpose: 'Real-time price feed for premium calculation',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    status: 'completed',
  },
];

export const riskHistory = [
  { time: '00:00', casperSwap: 20, friendlyMarket: 45, nexusDEX: 55, casperLend: 15, stakeVault: 38 },
  { time: '04:00', casperSwap: 22, friendlyMarket: 48, nexusDEX: 58, casperLend: 16, stakeVault: 40 },
  { time: '08:00', casperSwap: 21, friendlyMarket: 52, nexusDEX: 62, casperLend: 17, stakeVault: 42 },
  { time: '12:00', casperSwap: 23, friendlyMarket: 58, nexusDEX: 70, casperLend: 18, stakeVault: 44 },
  { time: '16:00', casperSwap: 22, friendlyMarket: 62, nexusDEX: 75, casperLend: 17, stakeVault: 43 },
  { time: '20:00', casperSwap: 24, friendlyMarket: 65, nexusDEX: 80, casperLend: 19, stakeVault: 45 },
  { time: 'Now', casperSwap: 23, friendlyMarket: 67, nexusDEX: 82, casperLend: 18, stakeVault: 45 },
];
